#
# Espresso CircleCi 2.1 Configuration
#
version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.12
        environment:
          CGO_ENABLED: 0
          G111MODULE: "on"

jobs:
  espresso-test:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - dependency-cache-v1-{{ .Branch }}-
            - dependency-cache-v1-
            - repository-cache-v1-{{ .Branch }}-{{ .Revision }}
            - repository-cache-v1-{{ .Branch }}-
            - repository-cache-v1-
      - run: go mod download
      - save_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg
      - save_cache:
          key: repository-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: Run all tests
          command: go test -v ./...

workflows:
  version: 2
  espresso-ci:
    jobs:
      - espresso-test